import = [
	"~/.config/alacritty/tokyonight_night.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "CommitMono Nerd Font Propo"
style = "Bold"

[font.bold_italic]
family = "CommitMono Nerd Font Propo"
style = "Bold Italic"

[font.italic]
family = "CommitMono Nerd Font Propo"
style = "Italic"

[font.normal]
family = "CommitMono Nerd Font Propo"
style = "Regular"
